# kind: Pod
# apiVersion: v1
# metadata:
#   name: nginx 
# spec:
#   containers:
#   - name: nginx 
#     image: nginx:stable-otel

kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    name: nginx-test 
spec:
  containers:
  - name: nginx 
    image: nginx    

