kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: NNR1
  annotations:
    kubernetes:io/created-by: 'NNR3'
    jenkins.buid.url: 'https://jenkins.narendra.shop/expense/shop/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx
    

